## Array creation

In [1]:
import numpy as np
from numpy import *

In [2]:
arr=array([2,3,8,9,7])

print(arr)

[2 3 8 9 7]


In [3]:
print(arr.dtype);

int64


In [4]:
arr=array([2,3,8,9,7,5.5])

print(arr)
print(arr.dtype);

[2.  3.  8.  9.  7.  5.5]
float64


In [5]:
arr=array([2,3,8,9,7,5.5],int)

print(arr)
print(arr.dtype);

[2 3 8 9 7 5]
int64


In [6]:
arr=linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


## Numpy array using arange

In [7]:
#arr= arrange(start,end,step)
arr=np.arange(1,15)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
arr=np.arange(1,15,2)

print(arr)

[ 1  3  5  7  9 11 13]


## Numpy array using logspace

In [9]:
arr=logspace(1,40,5)

print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [10]:
print(arr[0])

10.0


In [11]:
print('%.2f' %arr[0])

10.00


## Numpy array using zeros

In [12]:
arr= zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [13]:
arr= zeros(5, int)

print(arr)

[0 0 0 0 0]


In [14]:
arr= zeros((4,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr= zeros((4,3,2))

print(arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


## create numpy array from list

In [16]:
list=[1,2,3,4,5,6]
arr=np.array(list)

arr    # not using print()

array([1, 2, 3, 4, 5, 6])

In [17]:
list=[[1,2,3,4],[5,6,7,8]]
arr=np.array(list)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
list=[[1,2,3,4],[5,6,7]]   # elements need to be equal
arr=np.array(list)
arr

<ipython-input-18-7c526ae41b93>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr=np.array(list)


array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

## matrix

In [19]:
matrix=np.full(5,10)

matrix

array([10, 10, 10, 10, 10])

In [20]:
matrix=np.full((4,3),10)

matrix

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
matrix=np.eye(3)

matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
matrix=np.diag([7,8,9])

matrix

array([[7, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])

## Random Generation in Numpy

In [23]:
arr= np.random.rand(5)

arr

array([0.71930547, 0.54046068, 0.91113676, 0.36578115, 0.19979485])

In [24]:
arr= np.random.rand(3,4)

arr

array([[0.22818536, 0.22367162, 0.50638153, 0.42892257],
       [0.01092216, 0.32251225, 0.25790774, 0.83151005],
       [0.49255532, 0.35855502, 0.55266057, 0.40914625]])

In [25]:
arr= np.random.rand(3,4,3)

arr

array([[[0.90097192, 0.02732649, 0.34017197],
        [0.05749571, 0.54512575, 0.19329501],
        [0.31662513, 0.04613006, 0.48741438],
        [0.95653684, 0.34100216, 0.99325277]],

       [[0.7725286 , 0.18684309, 0.46809553],
        [0.57163724, 0.94045898, 0.01262209],
        [0.08532876, 0.22871152, 0.0679459 ],
        [0.76577277, 0.02947895, 0.90203216]],

       [[0.3862638 , 0.11003456, 0.2564671 ],
        [0.59983936, 0.66585104, 0.45322836],
        [0.33022095, 0.90381905, 0.08782792],
        [0.02768195, 0.47217958, 0.43033455]]])

In [26]:
arr= np.random.randn(5)

arr

array([-0.57057927, -0.12096831, -1.03163236, -1.38130097, -0.5676861 ])

In [27]:
arr= np.random.randint(0,10,10)  # [0,10) range 10 elements

arr

array([3, 8, 9, 7, 4, 5, 0, 2, 5, 5])

In [28]:
arr= np.random.randint(1,15, (4,4))

arr

array([[ 7,  1, 12, 11],
       [ 1, 12, 12,  2],
       [ 9, 13,  3,  4],
       [13,  6,  2,  4]])

## Some functions in numpy

In [29]:
arr1=linspace(0,15,16)
print(arr1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [30]:
arr2=ones((4,3),int)
print(arr2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [31]:
arr1.ndim

1

In [32]:
arr2.ndim

2

In [33]:
arr1.shape

(16,)

In [34]:
arr2.shape

(4, 3)

In [35]:
arr1.size

16

In [36]:
arr2.size

12

In [37]:
arr1.dtype

dtype('float64')

In [38]:
arr2.dtype

dtype('int64')

In [39]:
arr1.data    #memory location

In [40]:
arr2.data

## indexing in numpy

In [41]:
arr=linspace(0,15,16)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [42]:
for data in arr:
    print(data,end=" ")

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 

In [43]:
for i in range(len(arr)):
    print(arr[i],end=" ")

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 

In [44]:
print(arr[1:5])

[1. 2. 3. 4.]


In [45]:
print(arr[:6])

[0. 1. 2. 3. 4. 5.]


In [46]:
print(arr[4:])

[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [47]:
arr1=arr[5:]
arr1

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [48]:
arr2=arr1.copy
arr2

<function ndarray.copy>

In [49]:
print(arr2)

<built-in method copy of numpy.ndarray object at 0x7f69e07e4e90>


## Reshape and ravel function in Numpy

In [50]:
arr =np.random.randint(1,15,(6,5))
arr

array([[ 7,  8,  9,  6,  3],
       [ 1,  8,  6, 14, 13],
       [ 4,  8,  6, 12,  1],
       [ 5,  9,  6,  4,  1],
       [12,  2,  4,  6,  5],
       [ 5, 12,  1,  4, 13]])

In [51]:
a1=arr[0:4,0:3]
a1

array([[7, 8, 9],
       [1, 8, 6],
       [4, 8, 6],
       [5, 9, 6]])

In [52]:
a1.shape

(4, 3)

In [53]:
arr1=a1.reshape(3,4)
arr1

array([[7, 8, 9, 1],
       [8, 6, 4, 8],
       [6, 5, 9, 6]])

In [54]:
arr2=a1.reshape(6,3) #total elements need to be equal
arr2

ValueError: cannot reshape array of size 12 into shape (6,3)

In [55]:
arr3=arr1.ravel()
arr3

array([7, 8, 9, 1, 8, 6, 4, 8, 6, 5, 9, 6])

## Arithmetic Operation in Numpy

In [56]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
print(arr+arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [58]:
print(arr-arr)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [59]:
print(arr*arr)

[  1   4   9  16  25  36  49  64  81 100 121 144]


In [60]:
print(arr/arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [61]:
arr=np.arange(0,13)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-62-00bb58cbf2e7>:1: RuntimeWarning: invalid value encountered in true_divide
  print(arr/arr)


In [63]:
arr1=a1.reshape(3,4)
arr1

array([[7, 8, 9, 1],
       [8, 6, 4, 8],
       [6, 5, 9, 6]])

In [64]:
arr2=a1.reshape(6,2)
arr2

array([[7, 8],
       [9, 1],
       [8, 6],
       [4, 8],
       [6, 5],
       [9, 6]])

In [65]:
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (3,4) (6,2) 

In [66]:
print(arr1+arr2.reshape(3,4))

[[14 16 18  2]
 [16 12  8 16]
 [12 10 18 12]]


In [67]:
arr3=arr1+arr2.reshape(3,4)
arr3

array([[14, 16, 18,  2],
       [16, 12,  8, 16],
       [12, 10, 18, 12]])

In [68]:
arr3.sum(axis=0)

array([42, 38, 44, 30])

In [69]:
arr3.sum(axis=1)

array([50, 52, 52])

## Array selection in Numpy

In [70]:
arr=np.random.randint(1,15,(6,5))
arr

array([[ 3,  8, 12,  9,  7],
       [ 2, 14, 10,  2,  7],
       [14,  4,  3,  4, 10],
       [10,  1,  2,  8,  7],
       [ 6,  6,  1,  2, 13],
       [ 6,  2,  8, 13,  2]])

In [71]:
a1=arr[0:4,0:3]
a1

array([[ 3,  8, 12],
       [ 2, 14, 10],
       [14,  4,  3],
       [10,  1,  2]])

In [72]:
a2=arr[4:,]
a2

array([[ 6,  6,  1,  2, 13],
       [ 6,  2,  8, 13,  2]])

In [73]:
a3=arr[3:5,2:4]
a3

array([[2, 8],
       [1, 2]])

In [74]:
bool_m = a1>6 # if ai>6 true else false
bool_m

array([[False,  True,  True],
       [False,  True,  True],
       [ True, False, False],
       [ True, False, False]])